name: single-job Github Action
on : push
jobs: 
    single-jon:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "Repository ${{ github.repository }}"
            - run: echo "Branch ${{ github.ref_name }}"
            - run: echo "Commit SHA ${{ gthub.sha }}"
