name: Secrets
env:
  API_KEY: ${{ secrets.API_KEY }}
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: echo "key length: ${#API_KEY}"